### ISSUE TITLE
Repicient: nome equivocado

### ISSUE THREAD

**Issue by meleu** [fabianoobispo/FastFeet#1]
Olá @fabianoobispo , aqui é um colega de bootcamp.

Criei essa issue só pra te alertar que a grafia correta para Destinatário em inglês é **Recipient**, e observei que por todo o seu código você está usando Re**pic**ient.

Espero ter ajudado.

Forte abraço e bora codar!

**Comment by fabianoobispo** [comment]
Muito obrigado, passou batido kkkkk vou corrigir
